### ISSUE TITLE
Harbour and Airfield in India have the wrong owner

### ISSUE THREAD

**Issue by simon33-2** [triplea-maps/world_war_ii_global#1]
The Harbour and Airfield in India should be owned by UK_Pacific, not Britain/UK_Europe

**Comment by ron-murhammer** [comment]
@simon33-2 Can you get some other experienced global players to verify this?

**Comment by simon33-2** [comment]
I've posted a question - but there's no doubt in my mind.

**Comment by panther2** [comment]
This is already in the game notes:

Quote from game notes:
**Rules specific to 1940 the engine does not do, but you must follow:** 
...
 * (EM) India (UK Pacific) must pay for repairing any damaged facilities on the pacific half of the board (instead of London paying) (use edit mode to subtrack the PUs from India and give back to London).
...

**Comment by panther2** [comment]
Also please see
https://github.com/triplea-game/triplea/issues/1029#issuecomment-237338881

**Comment by simon33-2** [comment]
Here's a diff of the fix, to the file: games/ww2global40_2nd_edition.xml (same fix for other 4 files in the games directory):
6014c6014
< 						<unitPlacement unitType="harbour" territory="Kwangtung" quantity="1" owner="UK_Pacific"/>
---
> 						<unitPlacement unitType="harbour" territory="Kwangtung" quantity="1" owner="British"/>
6017c6017
< 						<unitPlacement unitType="harbour" territory="Malaya" quantity="1" owner="UK_Pacific"/>
---
> 						<unitPlacement unitType="harbour" territory="Malaya" quantity="1" owner="British"/>
6027,6028c6027,6028
< 						<unitPlacement unitType="airfield" territory="India" quantity="1" owner="UK_Pacific"/>
< 						<unitPlacement unitType="harbour" territory="India" quantity="1" owner="UK_Pacific"/>
---
> 						<unitPlacement unitType="airfield" territory="India" quantity="1" owner="British"/>
> 						<unitPlacement unitType="harbour" territory="India" quantity="1" owner="British"/>

I'll see if I can crack the pull request on the weekend.

**Comment by panther2** [comment]
Great - so the issue was caused by the initial setup only, meaning that everything else is just working fine.

**Comment by simon33-2** [comment]
This fix has been merged. Close issue
