### ISSUE TITLE
Retreat rule issue

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_global#12]
TripleA should not offer the attacker's option to retreat, if after a round of combat:

- in a seazone only a "defending" Transport is left
- in a territory only a "defending" AAA gun is left
- in a seazone only attacking air units are left as well as only a "defending" Submarine.

If these scenarios occur, the battle is over:

- the Transport is autodestroyed, given the attacker still has units with an attack value.
- the AAA gun is autodestroyed.
- the Submarine cannot be hit by air units

**Comment by DanVanAtta** [comment]
This would be updated on the game engine level, would not be map specific necessarily (rule set specific)

**Comment by panther2** [comment]
@DanVanAtta 
I sometimes have problems deciding whether an issue is engine-specifc or map-(ruleset)-specific.
The concept of an AA gun being a casualty, for example, has been introduced by the Global ruleset. So the related issue stated above only applies to Global and wwII_v5. In older games the AA gun has been subject to capture (so this would not be an issue there).
I think in general one can say, that the retreat rule of course applies to probably every WWII map, but the consequences do depend on the ruleset-specific unit charateristics, too.
(Another example would be that in very old game versions, the Tranport had an defense value of '1'.)

I will open an issue at the engine-repository, referencing this one. That should solve my conflict.
Do you have sort of a rule of thumb for me, concerning the above stated problem?

**Comment by DanVanAtta** [comment]
It can be difficult to know the difference. a decent rule of thumb is:
- it's a map only problem if you can fix it by only updating XML or adding/moving image files in the map folder.
- it's a game engine problem if you have to update code to fix the issue.

Will close since there is a game engine ticket covering the same.
