### ISSUE TITLE
Combined Turn Posting

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_global#21]
@simon33-2 

With commits

https://github.com/triplea-maps/world_war_ii_global/commit/fab05d63f8d5d55862d333d5063f2efd1d904143
and 
https://github.com/triplea-maps/world_war_ii_global/commit/d4fb35979fde95fcf5b4be81e5b7fe7010d141ef

you introduced "Combined Turn Posting" as a new feature.

I have tested this and found out:

- I get a separate turn post for USA, then
- I get a seperate turn post for China, then
- I get a combined turn post for USA, China, British/UK_Pacific

later 

- I get a separate turn post for Anzac, then
- I get a combined turn post for Anzac and France.

**I could not figure out how to get a separate turn post for either UK and France.
I could not figure out how to deactivate the combined turn post.**

While I can of course imagine scenarios where a combination may be useful as additional "service",
it seems that redundant information is enforced with every posting.
Of course there is no need to post China, when China has been taken out, and the player can always choose not to post China in this case, so here the combination is reasonable.
But I can't imagine a scenario where you would not post USA and wait until the information is given afer the British moves.

Can you please explain? What have I missed?

Thanks a lot :smile:

**Comment by panther2** [comment]
@simon33-2 

Also have you considered that there is sort of a "turn post character limit" on axisandallies.org?
In case there are large battles, added with dice results, this limit will be reached with posting only one nation, sometimes. It will be reached quicker when posting combined turns for sure.

**Comment by simon33-2** [comment]
Quite - that's how it works. I would have turned off posting for USA, China and ANZAC but that wouldn't work very well for games with more than 2 players.

Re: turn post character limit, Hmm, if we would hit this can it be increased?

There is no way to deactivate it beyond editing the XML.

So you aren't a fan? Lucky I checked here; not sure why I didn't get an email notification.

**Comment by simon33-2** [comment]
Oh, and BTW, if you want to get a single nation post for France, you can use the post item in the file menu to post a manual post. But might not be so good with UK. Could only show UK_Pac.

**Comment by simon33-2** [comment]
Why would you want to post USA if the summary is included at the end of UK?

**Comment by panther2** [comment]
Thank you for your answers.

> So you aren't a fan?

Actually, I do like your idea, I got just confused regarding the ingame results of the coding, that is why I asked.

I especially like
- that the player can decide to post USA, China and Anzac individually
- the possibility of a combined turn post that shows the result of the Allied nations that act consecutively

I do not like though
- that the player cannot decide to post the British and French turn individually
- that even if the player decided to post USA, China and Anzac individually, their turns are posted redundantly with British/French.

For me an optimal solution would be
- leave the individual turn post solution as it was before those commits
but
- when it comes to as well the British as the French turn post offer an individual turn post and / or a combined post for USA/China/British and Anzac/French. 

This way the player has the chance to negate turn postings for USA/China/Anzac and when on British/French will be able to combine the turn post(s), avoiding redundant information.

I am not sure if this is codable in the xml though.

> Why would you want to post USA if the summary is included at the end of UK?

Right, I mixed up the turn order, forget about that part of my above statement.

> Re: turn post character limit, Hmm, if we would hit this can it be increased?

Some players even include territory and production summary and dice statistics. So the limit might be reached quickly. I don't know if it can be increased. Maybe ask djensen.

> not sure why I didn't get an email notification.

Have you tried the Web-notifications to be set via the Settings/Notifications?

**Comment by simon33-2** [comment]
Would require a pretty tricky engine enhancement to allow combined posting for either British+UK_Pacific or Americans+Chinese+British+UK_Pacific.

I think it's going to be either the way it is or the way it was.

**Comment by panther2** [comment]
In my naive thinking I hoped something like this could work:

```
<step name="UK_PacificEndTurn" delegate="endTurn" player="UK_Pacific">
	    <stepProperty name="turnSummaryPlayers" value="British:UK_Pacific"/>
            <stepProperty name="turnSummaryPlayers" value="Americans:Chinese:British:UK_Pacific"/>
</step>
```
or

```
<step name="UK_PacificEndTurn" delegate="endTurn" player="UK_Pacific">
        <stepProperty name="turnSummaryPlayers" value="British:UK_Pacific"/>
 </step>
<step name="UK_PacificEndTurn" delegate="endTurn" player="UK_Pacific">
        <stepProperty name="turnSummaryPlayers" value="Americans:Chinese:British:UK_Pacific"/>
 </step>
```

... but both seems to fail.

**Comment by simon33-2** [comment]
Yeah, I think there can only be one value of each property. That was the China getting convoyed bug - the second setting overwrote the first.

**Comment by simon33-2** [comment]
@panther2 
Can I suggest this issue should be closed? There is no proposed further action.
