### ISSUE TITLE
Remove experimental data?

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_global#22]
@simon33-2 

Now that there is
https://github.com/triplea-maps/Global_1940_Redesign_HouseRules
are you going to revert the latest commits that added the experimental data/files to this repo?

**Comment by simon33-2** [comment]
I reverted the one with the SBR only bomber but the one with Canada I'm thinking of leaving there. Perhaps some playtesting would show that's a bad idea but let's wait and see.

**Comment by panther2** [comment]
@simon33-2 
Having no overwiew regarding the many house roule attempts myself, I wonder if the game
**G40Redesign_Test.xml** to be found in this repo is different from your approach in your new 
repo https://github.com/triplea-maps/Global_1940_Redesign_HouseRules ?
Are these different games?

**Comment by simon33-2** [comment]
Yeah,
The one in this repo just has:
- Canada as a power
- reversed Novgorod & Volgograd objectives
- Most of BM3
- USSR DOW on Japan nullifying Mongolia
- Standard tech.

Perhaps some other things but it's more of a development of BM3 than wild experimentation as found in the redesign stuff.

**Comment by panther2** [comment]
I see, thanks!

**Comment by panther2** [comment]
@simon33-2 
I closed this just a bit too early ... I realized the new changes had no corresponding update of the triplea_maps.yaml. So you are waiting to add some more stuff to this map/xml?

**Comment by simon33-2** [comment]
Updating the version number in triplea_maps.yaml achieves so little! It isn't checked often, for a start, updates aren't mandatory. I just tell people to remove and re-install the maps these days.

**Comment by simon33-2** [comment]
I suppose since I have a PR open for triplea_maps.yaml I can add this change to it.

**Comment by panther2** [comment]
> Updating the version number in triplea_maps.yaml achieves so little! It isn't checked often, for a start, updates aren't mandatory. I just tell people to remove and re-install the maps these days.

Agreed. that's how I do it all the time. I watch all the repositories I am interested in and redownload whenever there is a change. I hope we will find a better solution for automated map updates one day.

> I suppose since I have a PR open for triplea_maps.yaml I can add this change to it.

Good idea to update the triplea_maps.yaml from time to time. At least some users get noticed then.
