### ISSUE TITLE
oztea fix

### ISSUE THREAD

**Issue by beelee1** [triplea-maps/world_war_ii_global#27]
@simon33-2 or @panther2  
Hope this is the right place to ask. Did a small fix for oztea 41. It said it could be merged automatically. I tried to click on master to compare but it said there was nothing to compare. So Idk if it went through or if I did it right or not.

Just wanted to make you guys aware of it. Thanks

**Comment by simon33-2** [comment]
Can you push up the fix in an unzipped form?

**Comment by beelee1** [comment]
so just the xml or just take it out of master ?

**Comment by simon33-2** [comment]
just the xml if that is all that has changed.

**Comment by beelee1** [comment]
ok
