### ISSUE TITLE
"Add combinedTurns to UK Pacific place" needs to be applied to other XML-files

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_global#36]
#35 at the moment has only been applied to ww2global40_2nd_edition.xml
Likely every xml included in this map needs that fix, too.

(I put it on my todo-list. Everybody feel free to apply the changes, however.)

**Comment by simon33-2** [comment]
@panther2 That's done. Closing the issue.

**Comment by panther2** [comment]
Thank you, @simon33-2 !
