### ISSUE TITLE
Do we need Alpha3.xml and some txt files in the games-subfolder?

### ISSUE THREAD

**Issue by panther2** [triplea-maps/world_war_ii_global#9]
IMHO we can remove Alpha3.xml. I have never seen anyone playing this for years. Assuming it reflects the latest ruleset before 2nd Edition was published, the difference is 
- Korea is part of the Soviet-Mongolian Defense Pact in 2nd Ed.
- In 2nd Ed. setup there is one UK Infantry less in Egypt
- 2nd Ed. map merged Yukon Territory with British Columbia

2nd Edition has superseded Alpha3. No need to update it any longer.

Also there are two "Veqryn"-xml.txt -files. Not to negate the efforts creating these files but none of it has been updated in the past - so there would be some effort necessary to make them playable again. Do we need to keep them?

**Comment by simon33-2** [comment]
I could go either way. One could argue it could remain for completeness or that it should go because it's redundant. Although if no one uses it, I see your point. If the others want this, I can push up that change with #8.

**Comment by panther2** [comment]
Done - as part of #13
